/**
 * The workspace's conversations — one source of truth for both the inbox (1a)
 * and the queue table (1c), which previously carried separate copies of the
 * same people. Shaped from the design's demo data.
 */
import type { CannedReply, Conversation } from '../types';

export const conversations: Conversation[] = [
    {
        id: 1,
        name: 'Amanda Smith',
        note: 'VIP · 11 orders',
        channel: 'WhatsApp',
        subject: 'Package not delivered',
        preview: 'Where is my package?? It was due yesterday',
        policy: 'VIP · 5 min',
        waiting: '04:12',
        state: 'breached',
        status: 'open',
        assignee: null,
        filters: ['orders'],
        phone: '+44 7700 900412',
        previousConversations: 4,
        messages: [
            { id: 1, sender: 'customer', time: '10:59', text: 'Where is my package?? It was due yesterday and nobody has told me anything.' },
            { id: 2, sender: 'customer', time: '11:01', text: 'Order 204118. I have been a customer for three years, this is the first time.' },
            {
                id: 3,
                sender: 'rule',
                time: '11:02',
                rule: 'VIP + delivery keyword',
                text: 'Priority raised to High. Target first response reduced to 5 minutes.',
            },
            {
                id: 4,
                sender: 'agent',
                time: '11:05',
                text: 'Amanda, I am sorry — I can see 204118 was scanned into the Leeds depot and stopped there. I am dispatching a replacement today on next-day, no charge.',
            },
            { id: 5, sender: 'customer', time: '11:06', text: 'Oh thank you. That is a relief.' },
        ],
        customer: { since: 'Mar 2023', orders: 11, lifetime: '£1,842', tags: ['VIP', 'Delivery'] },
        order: {
            ref: '#204118',
            placed: '19 Aug',
            items: '2 items · £96.00',
            courier: 'Evri · last scan Leeds depot, 20 Aug',
            status: 'Delayed in transit',
        },
        sla: { policy: 'VIP · 5 min', firstResponse: 'Missed by 04:12', resolution: '4 hours', hours: '08:00–20:00 GMT' },
        recent: [
            { subject: 'Sizing question', meta: '2 Jul · resolved in 6m' },
            { subject: 'Order 198220 late', meta: '14 May · resolved in 22m' },
            { subject: 'Discount code', meta: '3 Apr · resolved in 9m' },
        ],
    },
    {
        id: 2,
        name: 'Sarah Jenkins',
        note: 'Return in progress',
        channel: 'WhatsApp',
        subject: 'Damaged item, order #192837',
        preview: 'I need to return order #192837 — the shirt arrived ripped',
        policy: 'Standard · 15 min',
        waiting: '02:47',
        state: 'breached',
        status: 'open',
        assignee: 'Alex A.',
        filters: ['returns'],
        phone: '+44 7700 900118',
        previousConversations: 2,
        messages: [
            { id: 1, sender: 'customer', time: '10:42', text: 'I received order #192837 yesterday but the shirt is ripped.' },
            { id: 2, sender: 'agent', time: '10:45', text: 'Sorry about that, Sarah. Could you send a photo of the damage?' },
            { id: 3, sender: 'customer', time: '10:47', text: 'Sent. I needed it for an event this weekend — can I get a replacement fast?' },
        ],
        customer: { since: 'Jan 2024', orders: 4, lifetime: '£312', tags: ['Returns'] },
        order: {
            ref: '#192837',
            placed: '16 Aug',
            items: '1 item · £48.00',
            courier: 'Royal Mail · delivered 19 Aug',
            status: 'Return requested',
        },
        sla: { policy: 'Standard · 15 min', firstResponse: 'Missed by 02:47', resolution: '8 hours', hours: '08:00–20:00 GMT' },
        recent: [{ subject: 'Where is my order', meta: '2 Aug · resolved in 14m' }],
    },
    {
        id: 3,
        name: 'Elena Rodriguez',
        note: 'Wholesale lead',
        channel: 'WhatsApp',
        subject: 'Bulk quote, 50 jackets',
        preview: 'Can I get a quote for a bulk order of 50 jackets?',
        policy: 'Standard · 15 min',
        waiting: '11:30',
        state: 'warning',
        status: 'open',
        assignee: 'Priya O.',
        filters: ['orders'],
        phone: '+44 7700 900204',
        previousConversations: 1,
        messages: [
            { id: 1, sender: 'customer', time: '09:00', text: 'Can I get a quote for a bulk order of 50 jackets?' },
            { id: 2, sender: 'agent', time: '09:12', text: 'Absolutely — what sizes and by when do you need them?' },
        ],
        customer: { since: 'Nov 2025', orders: 1, lifetime: '£240', tags: ['Wholesale'] },
        order: null,
        sla: { policy: 'Standard · 15 min', firstResponse: 'Met in 12m', resolution: '8 hours', hours: '08:00–20:00 GMT' },
        recent: [],
    },
    {
        id: 4,
        name: 'Michael Chen',
        note: null,
        channel: 'Instagram',
        subject: 'Shipping to Canada',
        preview: 'Do you ship to Canada?',
        policy: 'Standard · 15 min',
        waiting: '14:02',
        state: 'ontime',
        status: 'open',
        assignee: null,
        filters: [],
        phone: '@m.chen',
        previousConversations: 0,
        messages: [{ id: 1, sender: 'customer', time: '11:04', text: 'Do you ship to Canada?' }],
        customer: { since: 'First contact', orders: 0, lifetime: '£0', tags: [] },
        order: null,
        sla: { policy: 'Standard · 15 min', firstResponse: 'Due in 15m', resolution: '8 hours', hours: '08:00–20:00 GMT' },
        recent: [],
    },
    {
        id: 5,
        name: 'Priya Raman',
        note: null,
        channel: 'Instagram',
        subject: 'Restock question',
        preview: 'Is the ocean blue jacket back in stock yet?',
        policy: 'Standard · 15 min',
        waiting: '22:18',
        state: 'ontime',
        status: 'open',
        assignee: 'Marcus W.',
        filters: [],
        phone: '@priya.r',
        previousConversations: 3,
        messages: [{ id: 1, sender: 'customer', time: '10:38', text: 'Is the ocean blue jacket back in stock yet?' }],
        customer: { since: 'Feb 2024', orders: 6, lifetime: '£690', tags: ['VIP'] },
        order: null,
        sla: { policy: 'VIP · 5 min', firstResponse: 'Met in 3m', resolution: '4 hours', hours: '08:00–20:00 GMT' },
        recent: [],
    },
    {
        id: 6,
        name: 'Tomas Berg',
        note: null,
        channel: 'WhatsApp',
        subject: 'Invoice copy',
        preview: 'Could you send a copy of the invoice for August?',
        policy: 'Standard · 15 min',
        waiting: '31:05',
        state: 'ontime',
        status: 'open',
        assignee: null,
        filters: [],
        phone: '+44 7700 900771',
        previousConversations: 1,
        messages: [{ id: 1, sender: 'customer', time: '10:29', text: 'Could you send a copy of the invoice for August?' }],
        customer: { since: 'Jun 2024', orders: 9, lifetime: '£1,120', tags: ['Wholesale'] },
        order: null,
        sla: { policy: 'Standard · 15 min', firstResponse: 'Due in 4m', resolution: '8 hours', hours: '08:00–20:00 GMT' },
        recent: [],
    },
    {
        id: 7,
        name: 'James Wilson',
        note: null,
        channel: 'Instagram',
        subject: 'Refund received',
        preview: 'Thanks for the quick refund!',
        policy: 'Standard · 15 min',
        waiting: '—',
        state: 'closed',
        status: 'resolved',
        assignee: 'Alex A.',
        filters: ['returns'],
        phone: '@jwilson',
        previousConversations: 2,
        messages: [{ id: 1, sender: 'customer', time: '08:00', text: 'Thanks for the quick refund!' }],
        customer: { since: 'Sep 2024', orders: 3, lifetime: '£188', tags: [] },
        order: null,
        sla: { policy: 'Standard · 15 min', firstResponse: 'Met in 4m', resolution: 'Closed', hours: '08:00–20:00 GMT' },
        recent: [],
    },
];

export const cannedReplies: CannedReply[] = [
    { command: '/refund', label: 'start a refund' },
    { command: '/quote', label: 'bulk pricing' },
    { command: '/track', label: 'delivery status' },
    { command: '/note', label: 'internal' },
];

export const agents: string[] = ['Alex A.', 'Priya O.', 'Marcus W.', 'Lena O.'];
